### ISSUE TITLE
ImportError: cannot import name SortableModelAdmin

### ISSUE THREAD

**Issue by pixelead0** [darklow/django-suit#622]
If this is a bug please specify versions you're using first.

Django version: 1.10.7
Django Suit version: git://github.com/darklow/django-suit.git@v2#egg=django-suit
Python version: 2.7.3

Issue:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.virtualenvs/django-project/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.virtualenvs/django-project/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/home/vagrant/.virtualenvs/django-project/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vagrant/.virtualenvs/django-project/local/lib/python2.7/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/home/vagrant/.virtualenvs/django-project/local/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/home/vagrant/.virtualenvs/django-project/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/vagrant/.virtualenvs/django-project/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/vagrant/src/applications/admin.py", line 11, in <module>
    from suit.admin import SortableModelAdmin

```

**Comment by ganmedia** [comment]
Instead of "from suit.admin import SortableModelAdmin"
Use "from suit.sortables import SortableModelAdmin"
