### ISSUE TITLE
Looks like it doesn't work with Django 3

### ISSUE THREAD

**Issue by Kryzhanivskyi** [darklow/django-suit#754]
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/developer/PycharmProjects/voorg/voorg_venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/developer/PycharmProjects/voorg/voorg_venv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/developer/PycharmProjects/voorg/voorg_venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/home/developer/PycharmProjects/voorg/voorg_venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/home/developer/PycharmProjects/voorg/voorg_venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/developer/PycharmProjects/voorg/voorg_venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/developer/PycharmProjects/voorg/voorg_venv/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/developer/PycharmProjects/voorg/voorg_venv/lib/python3.6/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/home/developer/PycharmProjects/voorg/voorg_venv/lib/python3.6/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/developer/PycharmProjects/voorg/voorg_venv/lib/python3.6/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/developer/PycharmProjects/voorg/voorg_venv/lib/python3.6/site-packages/suit/admin.py", line 8, in <module>
    from suit.widgets import NumberInput, SuitSplitDateTimeWidget
  File "/home/developer/PycharmProjects/voorg/voorg_venv/lib/python3.6/site-packages/suit/widgets.py", line 6, in <module>
    from django.contrib.admin.templatetags.admin_static import static
ModuleNotFoundError: No module named 'django.contrib.admin.templatetags.admin_static'

**Comment by amureki** [comment]
Hey @Kryzhanivskyi 
I think, all the compatibility issues were solved in [v2 branch](https://github.com/darklow/django-suit/tree/v2). Probably you can try it out for your needs.

Please, also see https://github.com/darklow/django-suit/issues/475#issuecomment-408669565

**Comment by pulse-mind** [comment]
Hello
Look at my fork branch v2 too
Cheers

**Comment by pulse-mind** [comment]
Hi,
If you want a django3.2 version it is available on my fork branch v2
And I just finished the boostrap5.1 version, it is on a branch boostrap51 but I will do a pull request soon on v2
